name: data
on:
  schedule:
    - cron: 0 0 1 */3 *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./src/cpp.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/payroll/payroll-deductions-contributions/canada-pension-plan-cpp/cpp-contribution-rates-maximums-exemptions.html
          downloaded_filename: cpp.html
          postprocess: ./src/cpp.ts
